from recommendation_engine.basket_onboarding_info import Basket_onboarding_info
from recommendation_engine.basket_recommendation_engine import Basket_recommendation_engine
from octopusProducts.models import Tag, Recipe, Tag_recipe
from basket_porting.basket_to_port import Basket_to_port
from basket_porting.spider_manager import Spider_manager_controller
from basket_porting.thread_manager import Thread_manager
from django.utils import simplejson
from django.http import HttpResponse
import json

from octopusProducts.views import spider_view_test

info = Basket_onboarding_info(people = 2, budget = 60, tags = ["European", "Chinese", "Indian"], days = "")

a = Basket_recommendation_engine.create_onboarding_basket(info)

spider_view_test("some_request", a)


def spider_view(request, a):

    Spider_manager_controller.create_if_none()

    # for testing purposes
    email = "arnaudbenard13+test@gmail.com"
    password = "test123"

    product_details = data['products'] # List of product generated by the user

    thread_manager = Thread_manager()
    this_basket = Basket_to_port(request, email, password,
        product_details, thread_manager)



    Spider_manager_controller.add_basket_to_port(this_basket)

    this_basket.thread_manager.wait(15)

    response_data = this_basket.thread_manager.get_response() 
    return HttpResponse(json.dumps(response_data), content_type="application/json")