language: python
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
python:
  - "2.7"
notifications:
  email: false
install:
  - pip install -r stable-req.txt
  - npm install
  - bower install
