initial_ingredients = {

    "chicken": False,
    "olive oil": True,
    "ginger": True,
    "red pepper flakes": True,
    "brown sugar": True,
    "ketchup": True,
    "cider vinegar": True,
    "soy sauce": True,
    "sugar": True,
    "chile pepper": True,
    "pasta": False,
    "butter": False,
    "heavy cream": True,
    "tomato": False,
    "salt": True,
    "basil": False,
    "pepper": True,
    "garlic powder": True,
    "parmesan cheese": False,
    "black bean": False,
    "corn": False,
    "salsa": True,
    "cream cheese": False,
    "garlic": False,
    "cheddar cheese": False,
    "broth": False,
    "honey": True,
    "chili powder": True,
    "onion powder": True,
    "macaroni": False,
    "flour": True,
    "milk": False,
    "paprika": True,
    "cayenne pepper": True,
    "thyme": False,
    "onion": False,
    "beef": False,
    "celery": False,
    "tomato sauce": False,
    "barbecue sauce": True,
    "mustard seed and powder": True,
    "worcestershire sauce": True,
    "vinegar": True,
    "potato": False,
    "cornstarch": True,
    "green onion": False,
    "mayonnaise": True,
    "broccoli": False,
    "asparagus": False,
    "mozzarella": False,
    "sesame seed": True,
    "lemon juice": True,
    "sausage": False,
    "plum tomato": False,
    "parsley": True,
    "bacon": False,
    "green bean": False,
    "tomato paste": False,
    "oregano": True,
    "cottage cheese": False,
    "carrot": False,
    "rice": False,
    "bean sprouts": False,
    "water chestnut": True,
    "mushroom": False,
    "lettuce": False,
    "mustard prepared": True,
    "yogurt": False,
    "cumin": True,
    "cinnamon": True,
    "coriander": True,
    "masala": True,
    "cilantro": True,
    "tuna": False,
    "lentil": False,
    "oatmeal": False,
    "nutmeg": True,
    "hoisin sauce": True,
    "lemon": False,
    "swiss cheese": False,
    "stuffing": False,
    "rice vinegar": True,
    "rice wine": True,
    "baking powder": True,
    "cabbage": False,
    "eggplant": False,
    "sweet pepper": False,
    "processed cheese": False,
    "egg": False,
    "poultry seasoning": True,
    "turmeric": True,
    "vanilla": True,
    "pea": False,
    "turkey": False,
    "feta cheese": False,
    "cucumber": False,
    "ham": False,
    "baking soda": True,
    "romaine lettuce": False,
    "sour cream": False,
    "shrimp": False,
    "salmon": False,
    "hamburger": False,
    "bouillon": False,
    "dill": True,
    "clam": False,
    "tortilla": False,
    "horseradish": True,
    "cod": False,
    "zucchini": False,
    "wine vinegar": True,
    "snap pea": False,
    "cocoa powder": True,
    "margarine": False,
    "artichoke": False,
    "smoke seasoning": True,
    "shallot": False,
    "canola oil": True,
    "curry powder": True,
    "raisin": False,
    "bean thread": True,
    "fish sauce": True,
    "cranberry": False,
    "cauliflower": False,
    "pimiento": True,
    "kidney bean": False,
    "cardamom": True,
    "clove": True,
    "sweet potato": False,
    "tabasco sauce": True,
    "cornmeal": True,
    "pine nuts": True,
    "caper": True,
    "scallop": False,
    "rosemary": True,
    "pesto": True,
    "applesauce": False,
    "fennel seeds": True,
    "allspice": True,
    "tofu": False,
    "chives": True,
    "white bean": False,
    "walnut": True,
    "maple syrup": True,
    "curry paste": True,
    "coconut milk or cream": True,
    "basmati rice": False,
    "english mustard": True,
    "chickpea": True,
    "spinach": False,
    "peanut butter": True,
    "brown rice": False,
    "chinese cabbage": False,
    "beef round cuts": False,
    "pumpkin": False,
    "pecan": True,
    "marshmallow": False,
    "pork": False,
    "tomato puree": False,
    "marjoram": True,
    "celery seed": True,
    "lime": False,
    "black olive": False,
    "avocado": False,
    "kale": False,
    "tarragon": True,
    "corned beef": False,
    "mint": True,
    "apple": False,
    "halibut": False,
    "saffron": True,
    "brussels sprout": False,
    "provolone": False,
    "five spice powder": True,
    "blue cheese": False,
    "egg substitute": False,
    "cannellini bean": False,
    "spaghetti squash": False,
    "pineapple": False,
    "coconut": False,
    "leek": False,
    "creme fraiche": False,
    "quinoa": False,
    "rhubarb": False,
    "hash browns": False,
    "beet": False,
    "snow pea": False,
    "cashew nut": True,
    "crouton": True,
    "artificial sweetener": True,
    "asiago cheese": False,
    "cremini mushroom": False,
    "romano cheese": False,
    "powdered sugar": True,
    "okra": False,
    "monosodium glutamate": True,
    "currant": True,
    "chili sauce": True,
    "chard": False,
    "yeast": True,
    "arborio rice": False,
    "prosciutto": False,
    "banana": False,
    "kalamata olive": False,
    "corn flour": False,
    "mandarin orange": False,
    "couscous": False,
    "strawberry": False,
    "cheese": False,
    "alfredo sauce": True,
    "oyster sauce": True,
    "sauerkraut": False,
    "crab": False,
    "pumpkin pie spice": True,
    "molasses": True,
    "pudding mix": False,
    "ricotta cheese": False,
    "coffee": False,
    "tahini": True,
    "bamboo shoot": False,
    "french style green bean": False,
    "lobster": False,
    "caraway seed": True,
    "miso": False,
    "bechamel": False,
    "poppy seed": True,
    "peanut": True,
    "gouda": False,
    "anchovy paste": True,
    "manzanilla olive": False,
    "corn syrup": True,
    "mango": False,
    "cream of tartar": True,
    "ice cream": False,
    "lamb": False,
    "grape": False,
    "marmalade": False,
    "sweetened condensed milk": False,
    "gorgonzola": False,
    "wasabi": True,
    "tomato juice": False,
    "sunflower seed": True,
    "venison": False,
    "chocolate": False,
    "red chile powder": True,
    "fennel": False,
    "wild rice": False,
    "gelatin": True,
    "turnip": False,
    "duck": False,
    "chutney": True,
    "pistachio": False,
    "fenugreek": True,
    "gruyere": False,
    "soymilk": False,
    "star anise": True,
    "baguette": False,
    "mussel": False,
    "haddock": False,
    "prune": False,
    "madeira": False,
    "pickle": False,
    "boursin cheese": False,
    "radish": False,
    "palm sugar": True,
    "pomegranate": False,
    "cherry": False,
    "blueberry": False,
    "tea": False,
    "bay leaf": True,
    "granola": False,
    "pancetta": False,
    "mascarpone": False,
    "orange": False,
    "squash": False,
    "alfalfa sprouts": False,
    "muscovado sugar": True,
    "catfish": False,
    "watermelon": False,
    "bulgur wheat": False,
    "grapefruit": False,
    "plum": False,
    "rose water": False,
    "rabbit": False,
    "galangal": True,
    "french fry": False,
    "greens": False,
    "pheasant": False,
    "red snapper": False,
    "hazelnut": True,

}


def determine_if_condiment(ingredient):
    try:
        ingredient.is_condiment = initial_ingredients[ingredient.name]
        return ingredient
    except KeyError:
        #item is to be deleted.
        return None